import { Metadata } from "next";
import {Exo} from "next/font/google";
import "./globals.css";
import Navbar from './_comp-nav/navbar/Navbar';
import Footer from "./_comp-nav/footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import Provider from "./_comp-nav/myProvider/Provider";
import  Contextcreatprovider  from '../context/Craetcontext';


const geistSans = Exo({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Freshcart",
  description: "Generated by create next app",
};

      export default function RootLayout({
        children,
      }: Readonly<{
        children: React.ReactNode;
      }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      

        <Provider>
        <Contextcreatprovider>
        <Navbar/>
        
        <div className="min-h-screen bg-zinc-100">
       <div className=" w-[95%] mx-auto pt-5 ">
        <Toaster />
       {children}

       
        </div>
        
        <Footer/>
        
        </div>
     
           </Contextcreatprovider>
       </Provider>

       

       

        </body>
    </html>
  );
}
